[package]
name = "display-info"
version = "0.2.1"
edition = "2021"
description = "Cross-platform get display info"
license-file = "LICENSE"
documentation = "https://docs.rs/display-info"
homepage = "https://github.com/nashaofu/display-info"
repository = "https://github.com/nashaofu/display-info.git"
keywords = ["display", "screen", "displayinfo", "display-info"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.22.3"

[target.'cfg(target_os="windows")'.dependencies]
sfhash = "0.1.1"
widestring = "1.0.2"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.39.0"
features = ["Win32_Foundation", "Win32_Graphics_Gdi"]

[target.'cfg(target_os="linux")'.dependencies.xcb]
version = "1.1.1"
features = ["randr"]
